//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTiemNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuanLyTiemNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2236309_alert_bell_notification_icon {
            get {
                object obj = ResourceManager.GetObject("2236309_alert_bell_notification_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2236309_alert_bell_notification_icon1 {
            get {
                object obj = ResourceManager.GetObject("2236309_alert_bell_notification_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2bcd380f2487f97b666bf7daf3468a02 {
            get {
                object obj = ResourceManager.GetObject("2bcd380f2487f97b666bf7daf3468a02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2bcd380f2487f97b666bf7daf3468a021 {
            get {
                object obj = ResourceManager.GetObject("2bcd380f2487f97b666bf7daf3468a021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2bcd380f2487f97b666bf7daf3468a022 {
            get {
                object obj = ResourceManager.GetObject("2bcd380f2487f97b666bf7daf3468a022", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5a368f3512baf4_6006576315135250450767 {
            get {
                object obj = ResourceManager.GetObject("5a368f3512baf4.6006576315135250450767", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a000b3c56e38207c3798c37d9deabd46 {
            get {
                object obj = ResourceManager.GetObject("a000b3c56e38207c3798c37d9deabd46", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_gif_png_14 {
            get {
                object obj = ResourceManager.GetObject("arrow-gif-png-14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap com_suon_1000_quan_3_ho_chi_minh_1610945586199910701_eatery_avatar_1625934445 {
            get {
                object obj = ResourceManager.GetObject("com-suon-1000-quan-3-ho-chi-minh-1610945586199910701-eatery-avatar-1625934445", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fast_foods_fastfood {
            get {
                object obj = ResourceManager.GetObject("fast-foods-fastfood", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fat_boy_eating_junk_food_mnf2g1 {
            get {
                object obj = ResourceManager.GetObject("fat-boy-eating-junk-food-mnf2g1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap KH8E {
            get {
                object obj = ResourceManager.GetObject("KH8E", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_bottled_water_mineral_water_spring_mineral_water_bottles_5a6e746642c9b9_2706330415171881982736 {
            get {
                object obj = ResourceManager.GetObject("kisspng-bottled-water-mineral-water-spring-mineral-water-bottles-5a6e746642c9b9.2" +
                        "706330415171881982736", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_bottled_water_mineral_water_spring_mineral_water_bottles_5a6e746642c9b91 {
            get {
                object obj = ResourceManager.GetObject("kisspng-bottled-water-mineral-water-spring-mineral-water-bottles-5a6e746642c9b91", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_bottled_water_mineral_water_spring_mineral_water_bottles_5a6e746642c9b92 {
            get {
                object obj = ResourceManager.GetObject("kisspng-bottled-water-mineral-water-spring-mineral-water-bottles-5a6e746642c9b92", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_bottled_water_mineral_water_spring_mineral_water_bottles_5a6e746642c9b93 {
            get {
                object obj = ResourceManager.GetObject("kisspng-bottled-water-mineral-water-spring-mineral-water-bottles-5a6e746642c9b93", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_coffee_tea_cappuccino_cafe_deciliter_black_coffee_5a993d3cd60264_4841130515199921248766 {
            get {
                object obj = ResourceManager.GetObject("kisspng-coffee-tea-cappuccino-cafe-deciliter-black-coffee-5a993d3cd60264.48411305" +
                        "15199921248766", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_coffee_tea_cappuccino_cafe_deciliter_black_coffee_5a993d3cd602641 {
            get {
                object obj = ResourceManager.GetObject("kisspng-coffee-tea-cappuccino-cafe-deciliter-black-coffee-5a993d3cd602641", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_coffee_tea_cappuccino_cafe_deciliter_black_coffee_5a993d3cd602642 {
            get {
                object obj = ResourceManager.GetObject("kisspng-coffee-tea-cappuccino-cafe-deciliter-black-coffee-5a993d3cd602642", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_coffee_tea_cappuccino_cafe_deciliter_black_coffee_5a993d3cd602643 {
            get {
                object obj = ResourceManager.GetObject("kisspng-coffee-tea-cappuccino-cafe-deciliter-black-coffee-5a993d3cd602643", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_fried_chicken_kfc_hamburger_french_fries_fried_chicken_5a90c402b21cd9_8164959515194368027296 {
            get {
                object obj = ResourceManager.GetObject("kisspng-fried-chicken-kfc-hamburger-french-fries-fried-chicken-5a90c402b21cd9.816" +
                        "4959515194368027296", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kjhkhj {
            get {
                object obj = ResourceManager.GetObject("kjhkhj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lovepik_com_400756917_roast_sausage {
            get {
                object obj = ResourceManager.GetObject("Lovepik_com-400756917-roast-sausage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mi_trung_7311 {
            get {
                object obj = ResourceManager.GetObject("mi-trung-7311", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new1 {
            get {
                object obj = ResourceManager.GetObject("new1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NicePng_tv_screen_png_109633 {
            get {
                object obj = ResourceManager.GetObject("NicePng_tv-screen-png_109633", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NicePng_tv_screen_png_1096331 {
            get {
                object obj = ResourceManager.GetObject("NicePng_tv-screen-png_1096331", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NicePng_tv_screen_png_1096332 {
            get {
                object obj = ResourceManager.GetObject("NicePng_tv-screen-png_1096332", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NicePng_tv_screen_png_1096333 {
            get {
                object obj = ResourceManager.GetObject("NicePng_tv-screen-png_1096333", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NicePng_tv_screen_png_1096334 {
            get {
                object obj = ResourceManager.GetObject("NicePng_tv-screen-png_1096334", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NicePng_tv_screen_png_1096335 {
            get {
                object obj = ResourceManager.GetObject("NicePng_tv-screen-png_1096335", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__1_ {
            get {
                object obj = ResourceManager.GetObject("pngegg (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__1_1 {
            get {
                object obj = ResourceManager.GetObject("pngegg (1)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__1_2 {
            get {
                object obj = ResourceManager.GetObject("pngegg (1)2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__1_3 {
            get {
                object obj = ResourceManager.GetObject("pngegg (1)3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__1_4 {
            get {
                object obj = ResourceManager.GetObject("pngegg (1)4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__1_5 {
            get {
                object obj = ResourceManager.GetObject("pngegg (1)5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__1_6 {
            get {
                object obj = ResourceManager.GetObject("pngegg (1)6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__1_7 {
            get {
                object obj = ResourceManager.GetObject("pngegg (1)7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngegg__1_8 {
            get {
                object obj = ResourceManager.GetObject("pngegg (1)8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing_com {
            get {
                object obj = ResourceManager.GetObject("pngwing.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing_com__1_ {
            get {
                object obj = ResourceManager.GetObject("pngwing.com (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngwing_com__2_ {
            get {
                object obj = ResourceManager.GetObject("pngwing.com (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap searching_magnifying_glass {
            get {
                object obj = ResourceManager.GetObject("searching-magnifying-glass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tra_chanh_tra_tac_tra_dao_luong_huu_khanh_quan_1_ho_chi_minh_1647095981464292958_eatery_avatar_1647491312 {
            get {
                object obj = ResourceManager.GetObject("tra-chanh-tra-tac-tra-dao-luong-huu-khanh-quan-1-ho-chi-minh-1647095981464292958-" +
                        "eatery-avatar-1647491312", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tra_chanh_tra_tac_tra_dao_luong_huu_khanh_quan_1_ho_chi_minh_1647095981464292958_eatery_avatar_16474913121 {
            get {
                object obj = ResourceManager.GetObject("tra-chanh-tra-tac-tra-dao-luong-huu-khanh-quan-1-ho-chi-minh-1647095981464292958-" +
                        "eatery-avatar-16474913121", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tra_chanh_tra_tac_tra_dao_luong_huu_khanh_quan_1_ho_chi_minh_1647095981464292958_eatery_avatar_16474913122 {
            get {
                object obj = ResourceManager.GetObject("tra-chanh-tra-tac-tra-dao-luong-huu-khanh-quan-1-ho-chi-minh-1647095981464292958-" +
                        "eatery-avatar-16474913122", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tra_chanh_tra_tac_tra_dao_luong_huu_khanh_quan_1_ho_chi_minh_1647095981464292958_eatery_avatar_16474913123 {
            get {
                object obj = ResourceManager.GetObject("tra-chanh-tra-tac-tra-dao-luong-huu-khanh-quan-1-ho-chi-minh-1647095981464292958-" +
                        "eatery-avatar-16474913123", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tra_chanh_tra_tac_tra_dao_luong_huu_khanh_quan_1_ho_chi_minh_1647095981464292958_eatery_avatar_16474913124 {
            get {
                object obj = ResourceManager.GetObject("tra-chanh-tra-tac-tra-dao-luong-huu-khanh-quan-1-ho-chi-minh-1647095981464292958-" +
                        "eatery-avatar-16474913124", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tra_chanh_tra_tac_tra_dao_luong_huu_khanh_quan_1_ho_chi_minh_1647095981464292958_eatery_avatar_16474913125 {
            get {
                object obj = ResourceManager.GetObject("tra-chanh-tra-tac-tra-dao-luong-huu-khanh-quan-1-ho-chi-minh-1647095981464292958-" +
                        "eatery-avatar-16474913125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tra_chanh_tra_tac_tra_dao_luong_huu_khanh_quan_1_ho_chi_minh_1647095981464292958_eatery_avatar_16474913126 {
            get {
                object obj = ResourceManager.GetObject("tra-chanh-tra-tac-tra-dao-luong-huu-khanh-quan-1-ho-chi-minh-1647095981464292958-" +
                        "eatery-avatar-16474913126", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tra_chanh_tra_tac_tra_dao_luong_huu_khanh_quan_1_ho_chi_minh_1647095981464292958_eatery_avatar_16474913127 {
            get {
                object obj = ResourceManager.GetObject("tra-chanh-tra-tac-tra-dao-luong-huu-khanh-quan-1-ho-chi-minh-1647095981464292958-" +
                        "eatery-avatar-16474913127", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tra_chanh_tra_tac_tra_dao_luong_huu_khanh_quan_1_ho_chi_minh_1647095981464292958_eatery_avatar_16474913128 {
            get {
                object obj = ResourceManager.GetObject("tra-chanh-tra-tac-tra-dao-luong-huu-khanh-quan-1-ho-chi-minh-1647095981464292958-" +
                        "eatery-avatar-16474913128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
